[ko]
  title = 'AIDIN Teleoperation 시스템 문서'
  weight = 1
  languageCode = 'ko'
  languageName = '한국어'
  [ko.params]
    landingPageName = '<i class="fa-fw fas fa-home"></i> 홈'

[[ko.menu.shortcuts]]
  pre = '<i class="fa-fw fab fa-github"></i> '
  name = 'GitHub Repo'
  url = 'https://github.com/aidin-lgit/aidin_rby1_teleop'
  weight = 10
